/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        // Brand palette
        brand: {
          50: "#effaf6",
          100: "#d6f1e7",
          200: "#afe3cf",
          300: "#7dcfb2",
          400: "#4db393",
          500: "#278b70",
          600: "#1f705c",
          700: "#1a594a",
          800: "#17483e",
          900: "#143c35",
          950: "#09251f",
        },
        // Neutral grays (for surfaces)
        surface: {
          0: "#ffffff",
          50: "#f8fafc",
          100: "#f1f5f9",
          200: "#e2e8f0",
          300: "#cbd5e1",
          400: "#94a3b8",
          500: "#64748b",
          600: "#475569",
          700: "#334155",
          800: "#1e293b",
          850: "#162032",
          900: "#0f172a",
          950: "#080f1e",
        },
        // Semantic colors
        success: "#22c55e",
        warning: "#f59e0b",
        danger: "#ef4444",
        info: "#3b82f6",
      },
      fontFamily: {
        sans: ["Inter", "system-ui", "sans-serif"],
        mono: ["JetBrains Mono", "Fira Code", "Cascadia Code", "monospace"],
      },
      fontSize: {
        "2xs": ["0.65rem", { lineHeight: "1rem" }],
      },
      spacing: {
        sidebar: "280px",
        toc: "240px",
        header: "60px",
      },
      maxWidth: {
        content: "780px",
      },
      typography: ({ theme }) => ({
        DEFAULT: {
          css: {
            "--tw-prose-body": theme("colors.surface[700]"),
            "--tw-prose-headings": theme("colors.surface[900]"),
            "--tw-prose-lead": theme("colors.surface[600]"),
            "--tw-prose-links": theme("colors.brand[600]"),
            "--tw-prose-bold": theme("colors.surface[900]"),
            "--tw-prose-counters": theme("colors.surface[500]"),
            "--tw-prose-bullets": theme("colors.surface[400]"),
            "--tw-prose-hr": theme("colors.surface[200]"),
            "--tw-prose-quotes": theme("colors.surface[900]"),
            "--tw-prose-quote-borders": theme("colors.brand[400]"),
            "--tw-prose-captions": theme("colors.surface[500]"),
            "--tw-prose-code": theme("colors.surface[900]"),
            "--tw-prose-pre-code": theme("colors.surface[200]"),
            "--tw-prose-pre-bg": theme("colors.surface[900]"),
            "--tw-prose-th-borders": theme("colors.surface[300]"),
            "--tw-prose-td-borders": theme("colors.surface[200]"),
            // Dark
            "--tw-prose-invert-body": theme("colors.surface[300]"),
            "--tw-prose-invert-headings": theme("colors.surface[50]"),
            "--tw-prose-invert-lead": theme("colors.surface[400]"),
            "--tw-prose-invert-links": theme("colors.brand[400]"),
            "--tw-prose-invert-bold": theme("colors.surface[50]"),
            "--tw-prose-invert-counters": theme("colors.surface[400]"),
            "--tw-prose-invert-bullets": theme("colors.surface[600]"),
            "--tw-prose-invert-hr": theme("colors.surface[700]"),
            "--tw-prose-invert-quotes": theme("colors.surface[100]"),
            "--tw-prose-invert-quote-borders": theme("colors.brand[500]"),
            "--tw-prose-invert-captions": theme("colors.surface[400]"),
            "--tw-prose-invert-code": theme("colors.surface[50]"),
            "--tw-prose-invert-pre-code": theme("colors.surface[300]"),
            "--tw-prose-invert-pre-bg": "rgb(0 0 0 / 50%)",
            "--tw-prose-invert-th-borders": theme("colors.surface[600]"),
            "--tw-prose-invert-td-borders": theme("colors.surface[700]"),
            maxWidth: "none",
            h1: { fontWeight: "800", letterSpacing: "-0.02em" },
            h2: { fontWeight: "700", letterSpacing: "-0.01em" },
            h3: { fontWeight: "600" },
            code: {
              backgroundColor: "transparent",
              padding: "0",
              fontWeight: "500",
            },
            "code::before": { content: '""' },
            "code::after": { content: '""' },
            pre: { padding: "0", backgroundColor: "transparent", margin: "0" },
            "pre code": { fontFamily: theme("fontFamily.mono").join(", ") },
            a: { textDecorationThickness: "1px", textUnderlineOffset: "2px" },
            table: { width: "100%", tableLayout: "auto" },
            "thead th": { paddingTop: "0.875em", paddingBottom: "0.875em" },
          },
        },
      }),
    },
  },
  plugins: [require("@tailwindcss/typography")],
};
